"""empty message

Revision ID: f82720d9d1ec
Revises: 
Create Date: 2021-02-21 11:04:15.834793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82720d9d1ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ninja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma', sa.String(), nullable=True),
    sa.Column('volltext', sa.String(), nullable=True),
    sa.Column('plz_arbeitsor', sa.Integer(), nullable=True),
    sa.Column('arbeitsort', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ninja')
    # ### end Alembic commands ###
